[package]
name = "Chomusuke"
version = "0.1.0"
authors = ["Luuk van Oijen <lazyluuk.channel@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.7.2"
env_logger = "0.7.1"
pretty_env_logger = "0.3.1"
log = "0.4.0"
regex = "1"
egg-mode = "0.13.0"
postgres = "0.15.2"
postgres-derive = "0.3"
